### ISSUE TITLE
List of expected variable or function

### ISSUE THREAD

**Issue by collegeimprovements** [qhwa/formular#6]
Thanks a lot for this awesome library. 
It's been super useful to us. 

Is it possible to get the expected variables or functions from given rule ?
e.g.

`Formular.expected_vars_or_funtions("role in [:a, :b, :c, :d]") #=> ["role"]`
`Formular.expected_vars_or_funtions("role in [:a, :b, :c, :d] and sum == 10") #=> ["role", "sum"] `

```elixir
 discount_formula = ~s"
   case order do
     # old books get a big promotion
     %{book: %{year: year}} when year < 2000 ->
       0.5
   
     %{book: %{tags: tags}} ->
       # Elixir books!
       if ~s{elixir} in tags do
         0.9
       else
         1.0
       end

     _ ->
       1.0
   end
 "

iex> Formular.expected_vars_or_funtions(discount_formula) #=> ["year", "tags"]
```

**Comment by qhwa** [comment]
Hi, @collegeimprovements do you need this to ensure the necessary binding variables will be provided?

For the book discount example, does it make more sense to return `["order"]`?

**Comment by collegeimprovements** [comment]
Hi @qhwa ,

Thanks a lot for the reply.
1. Yes, to ensure that we have the right required bindings in the data. If not, we can fail early.
2. Yes, ["order"] makes more sense.

**Comment by qhwa** [comment]
This requirement makes sense. Actually, I'm working on a new upgraded approach which:

- compile the config code into an Elixir module
- call the `run` function in the module, instead of using `Code.eval_quoted/2`. The performance will be significantly improved

With this approach, I need to know which variables/functions are used in the configuration code. So I'm thinking about adding some declaration express, like:

```elixir
# use's role
var role
 
role in [:a, :b, :c, :d]
```

It looks more explicit than automatically finding the variables by parsing the code.
I'd like to hear your opinion on it.

**Comment by collegeimprovements** [comment]
If it improves performance it's a great thing. Since we just pass data and don't make any network calls or db-calls performance has never been a problem with Formular.

Making it static would actually limit some part of dynamic nature. 
E.g. we save rules with a string that mostly look like an natural language and mostly non-tech people create it.

So, having a rule like 
```elixir
"role in [:admin, :consumer, :provider]"
```

will always be more natural then having it like:
```elixir
var role
"role in [:admin, :consumer, :provider]"
```
Also we store these rules in text field in db. 
So, from db-view: it would be self-evident when someone reads `role in [:admin, :provider]`, and approach with `var role; role in [:admin, :provider]` would look little verbose.

It would be great to support the introduction of declaring variables explicitly without deprecating current mechanism.
As in 99.99% cases there isn't any performance issue and when one have a performance issue we can declare the variables explicitly.

This library is actually been great for creating natural language like rules which people who don't know elixir can create and comprehand (e.g. people who figure out things just from UI or just from DB). If possible, please keep the original api as well.

**Comment by qhwa** [comment]
Thanks for the invaluable feedback, @collegeimprovements, and you have convinced me to keep the configuration code cleaner, at least to the one-lines. 

My proposal would be as such:

```
code = "role in [:admin, :provider]"
{:ok, _module} = Formular.compile(code, to: RoleChecker)

RoleChecker.run(role: :admin)
#=> true

RoleChecker.run(role: nil)
#=> false

RoleChecker.run([])
#=> {:error, {:missing_variable, :role}}
```

In this case, do you still need `Formular.expected_vars_or_funtions/1` to help ensure the data shape?

**Comment by collegeimprovements** [comment]
Thanks a lot @qhwa . 

```elixir
code = "role in [:admin, :provider]"
{:ok, _module} = Formular.compile(code, to: RoleChecker)
```
In this case we can't create placeholder dynamically. 
E.g. 

```elixir
rule = role in [:admin, :provider] and id in [42, 100]
```
If there is some function that can give `["role", "id"]` we can generate input boxes dynamically for them.

Does this approach require us to provide all possible variables beforehand ? In that case with more values we will have 2^-1 possibilities.
```
Let's say there are 2 possible input values(e.g. role, id) then to cover all cases don't we need to generate 4 rules ?
1. For role
2. For id
3. For role and id

And for 3 possible input values(e.g. role, id, type)
1. For role
2. For id
3. For type
4. for role, id
5. for role, type
6. for id, type
7. for role, id and type
```

**Comment by qhwa** [comment]
Yes, the `eval` APIs will still be there. And looks like the new API wouldn't save the work for you. Thank you for your detailed feedback. Let me understand your question better. Could you elaborate on how you would use the `Formular.expected_vars_or_funtions` function?

**Comment by collegeimprovements** [comment]
For our usecase: 

We kind of know the variable values before hand. However we don't know what variable a rule gonna have.
e.g. We know that we gonna have variables like: role, type, id, email, mobile. In near future we will add few more.
Though we don't know if a rule contains all of them, some of them or none of them.
Some of the rules we have right now are:

```elixir
"true"
"false"
"role in [:admin, :producer] and id not in [1,42,1000]"
"email in [...] and type in [...]"
"role in [...] or type == ~s(superuser)"
"true and id in [..exception_list..]"
"true and id in [..exception_list..] or role in [...]"
```

Currently all the rules work just with `Formular.eval`. 
It would be great if we can provide some whitelist of variables but only enforce them.
And if a rule require one of those variables and it's missing then we give `{:error, reason}`.
But if a rule doesn't require some of those variables then it's fine and we give `{:ok, value}`.

**Comment by qhwa** [comment]
In such a case, I feel that it's already there, although the output is not very friendly:

```elixir
iex> test_binding = [role: nil, name: nil] # you construct a test binding keyword list
...> rule1 = "role in [:admin]"  # valid rule
...> rule2 = "age >= 18"  # invalid rule using unexpected variable

...> Formular.eval(rule1, test_binding)
{:ok, true}

...> Formular.eval(rule2, test_binding)
warning: variable "age" does not exist and is being expanded to "age()", please use parentheses to remove the ambiguity or change the variable name
  nofile:1

{:error,
 %CompileError{description: "undefined function age/0", file: "nofile", line: 1}}
```

**Comment by collegeimprovements** [comment]
> In such a case, if the requirement is to validate a rule against invalid variables, I feel that it's already there, although the output is not very friendly:
Yes. I just want to make sure that this api will keep working 😅

This solves most of our usecases 😃

**Comment by qhwa** [comment]
I see. It's a fair feature. I'll add an API for it in the next release.

**Comment by qhwa** [comment]
Hi @collegeimprovements I've added an API called `Formular.used_vars/1`. You can use the master branch or `0.3.0-pre.2` version on hex.pm to give the new API a try now!

Feedback is welcome!

**Comment by collegeimprovements** [comment]
Thanks a lot @qhwa 😃

**Comment by collegeimprovements** [comment]
@qhwa  Just a periodic thank you for creating this lib 💛

**Comment by qhwa** [comment]
Hi @collegeimprovements, you're very welcome! I'm glad it is helpful to you.
